#!/usr/bin/env node
/**
 * Bug Fixer
 *
 * Reads the last bug-report.json and applies safe, mechanical fixes only.
 *
 *   missing-column   → writes ALTER TABLE migration to server/src/db/patches/
 *   undefined-route  → appends a 501 stub handler to the correct route file
 *   null-check       → prints the location and a suggested fix (not auto-applied)
 *
 * Never modifies business logic, payment flows, or auth middleware.
 *
 * Usage: npm run bug:fix
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath }  from 'node:url';
import { dirname, resolve, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = resolve(__dirname, '..');
const REPORT    = join(ROOT, 'bug-report.json');

if (!existsSync(REPORT)) {
  process.stderr.write('No bug-report.json found. Run: npm run bug:report\n');
  process.exit(1);
}

const report  = JSON.parse(readFileSync(REPORT, 'utf8'));
const errors  = report.errors ?? [];
const fixable = errors.filter(e => e.fix_category);

process.stdout.write(`\nBug Fix  (report from ${report.timestamp})\n`);
process.stdout.write(`${errors.length} issue(s) total, ${fixable.length} with a known fix category\n\n`);

if (fixable.length === 0) {
  process.stdout.write('Nothing to fix automatically.\n\n');
  process.exit(0);
}

const applied = [];
const manual  = [];

for (const err of fixable) {
  switch (err.fix_category) {
    case 'missing-column':  applyMissingColumn(err);  break;
    case 'undefined-route': applyUndefinedRoute(err); break;
    case 'null-check':
      manual.push({ err, reason: 'Null-check fixes are context-dependent — review the surrounding code.' });
      break;
    case 'missing-table':
      manual.push({ err, reason: 'Missing table — check server/src/db/migrate.ts and add a CREATE TABLE block.' });
      break;
    default:
      manual.push({ err, reason: `No handler for fix_category="${err.fix_category}"` });
  }
}

// ── Summary ───────────────────────────────────────────────────────────────────

process.stdout.write(`Applied: ${applied.length}\n`);
for (const a of applied) process.stdout.write(`  ✓ ${a}\n`);

if (manual.length > 0) {
  process.stdout.write(`\nRequires manual fix: ${manual.length}\n`);
  for (const { err, reason } of manual) {
    const loc = err.file ? `${err.file}${err.line ? ':' + err.line : ''}` : (err.route ?? err.type);
    process.stdout.write(`  ⚠  [${loc}] ${err.message}\n`);
    process.stdout.write(`     → ${err.suggestion ?? reason}\n`);
    process.stdout.write(`     Reason not auto-fixed: ${reason}\n`);
  }
}

process.stdout.write('\n');
process.exit(manual.length > 0 && applied.length === 0 ? 1 : 0);

// ── Fix: missing column ───────────────────────────────────────────────────────

function applyMissingColumn(err) {
  const { table, column } = parseColumnFromError(err);

  if (!table || !column) {
    manual.push({ err, reason: `Could not parse table/column from: "${err.message}"` });
    return;
  }

  const colType = inferColumnType(column);
  const patchDir = join(ROOT, 'server', 'src', 'db', 'patches');
  mkdirSync(patchDir, { recursive: true });

  const ts       = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const filename = `fix-${ts}-add-${table}-${column}.sql`;
  const path     = join(patchDir, filename);

  const backfill = colType.includes('TIMESTAMPTZ')
    ? `UPDATE ${table} SET ${column} = NOW() WHERE ${column} IS NULL;`
    : `-- UPDATE ${table} SET ${column} = <default> WHERE ${column} IS NULL;`;

  const sql = [
    `-- Auto-generated by npm run bug:fix`,
    `-- Fixes: missing column ${table}.${column}`,
    `-- Apply:  psql "$DATABASE_URL" -f server/src/db/patches/${filename}`,
    `--         (or add this to server/src/db/migrate.ts as a migration step)`,
    ``,
    `ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${column} ${colType};`,
    ``,
    backfill,
  ].join('\n');

  writeFileSync(path, sql);

  const rel = `server/src/db/patches/${filename}`;
  applied.push(`Created migration: ${rel}`);
  process.stdout.write(`  ✓ ${table}.${column} — migration written to ${rel}\n`);
  process.stdout.write(`    Apply: psql "$DATABASE_URL" -f ${rel}\n`);
}

// ── Fix: undefined route ──────────────────────────────────────────────────────

function applyUndefinedRoute(err) {
  const source = err.route ?? err.message ?? '';
  const m      = source.match(/(GET|POST|PUT|PATCH|DELETE)\s+(\/api\/[^\s"']+)/i);

  if (!m) {
    manual.push({ err, reason: `Could not parse HTTP method and path from: "${source}"` });
    return;
  }

  const method    = m[1].toLowerCase();
  const fullPath  = m[2];
  const routeFile = resolveRouteFile(fullPath);

  if (!routeFile) {
    manual.push({ err, reason: `Cannot map ${fullPath} to a known route file` });
    return;
  }

  const absPath = join(ROOT, routeFile);
  if (!existsSync(absPath)) {
    manual.push({ err, reason: `Route file not found on disk: ${routeFile}` });
    return;
  }

  const subPath = extractSubPath(fullPath);
  const src     = readFileSync(absPath, 'utf8');

  // Don't add a duplicate
  if (src.includes(`router.${method}('${subPath}'`)) {
    manual.push({ err, reason: `Handler for ${method.toUpperCase()} ${subPath} already exists in ${routeFile}` });
    return;
  }

  const stub = [
    ``,
    `// STUB: auto-generated by npm run bug:fix — replace with real implementation`,
    `router.${method}('${subPath}', (_req, res) => {`,
    `  res.status(501).json({ error: 'Not implemented' });`,
    `});`,
    ``,
  ].join('\n');

  const updated = src.replace(/^export default router;?\s*$/m, `${stub}\nexport default router;\n`);
  writeFileSync(absPath, updated === src ? src + stub : updated);

  applied.push(`Added stub: ${method.toUpperCase()} ${fullPath} → ${routeFile}`);
  process.stdout.write(`  ✓ Stub added: ${method.toUpperCase()} ${subPath} in ${routeFile}\n`);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function parseColumnFromError(err) {
  const msg = (err.message ?? '') + ' ' + (err.suggestion ?? '');

  // "column cu.created_at does not exist"
  let m = msg.match(/column ['""]?(\w+)\.(\w+)['""]? does not exist/i);
  if (m) return { table: aliasToTable(m[1]), column: m[2] };

  // "column created_at of relation content_unlocks"
  m = msg.match(/column ['""]?(\w+)['""]? of relation ['""]?(\w+)['""]?/i);
  if (m) return { table: m[2], column: m[1] };

  // "Missing column content_unlocks.created_at"
  m = msg.match(/missing column[:\s]+(\w+)\.(\w+)/i);
  if (m) return { table: m[1], column: m[2] };

  return { table: null, column: null };
}

function aliasToTable(alias) {
  const MAP = {
    cu: 'content_unlocks',
    cp: 'creator_profiles',
    u:  'users',
    c:  'content',
    t:  'transactions',
    s:  'subscriptions',
  };
  return MAP[alias] ?? alias;
}

function inferColumnType(column) {
  if (column.endsWith('_at'))                          return 'TIMESTAMPTZ DEFAULT NOW()';
  if (column.endsWith('_id'))                          return 'TEXT';
  if (column.startsWith('is_') || column.startsWith('has_')) return 'SMALLINT DEFAULT 0';
  if (column === 'status')                             return "TEXT DEFAULT 'pending'";
  if (/count|price|amount|fee|earnings/.test(column)) return 'NUMERIC(12,2) DEFAULT 0';
  if (/pct|percent|rate/.test(column))                return 'INTEGER DEFAULT 0';
  return 'TEXT';
}

const ROUTE_MAP = [
  ['/api/creators',      'server/src/routes/creators.ts'],
  ['/api/content',       'server/src/routes/content.ts'],
  ['/api/payments',      'server/src/routes/payments.ts'],
  ['/api/admin',         'server/src/routes/admin.ts'],
  ['/api/auth',          'server/src/routes/auth.ts'],
  ['/api/stripe',        'server/src/routes/stripe.ts'],
  ['/api/webhooks',      'server/src/routes/webhooks.ts'],
  ['/api/messages',      'server/src/routes/messages.ts'],
  ['/api/keys',          'server/src/routes/keys.ts'],
  ['/api/notifications', 'server/src/routes/notifications.ts'],
  ['/api/activity',      'server/src/routes/activity.ts'],
  ['/api/access-request','server/src/routes/accessRequests.ts'],
];

function resolveRouteFile(path) {
  for (const [prefix, file] of ROUTE_MAP) {
    if (path.startsWith(prefix)) return file;
  }
  return null;
}

function extractSubPath(fullPath) {
  const prefix = fullPath.match(/^(\/api\/[^/]+)/)?.[1] ?? '';
  return fullPath.slice(prefix.length) || '/';
}
